import fs from "node:fs"
import os from "node:os"
import path from "node:path"
import crypto from "node:crypto"
import { defaultMatcher } from "./ignore.js"
import { redact } from "./redact.js"
import { ScanError } from "../errors.js"

/** ext → [display name, family, kind]. kind: code | style | markup | data | config | doc */
export const LANGS = {
  ".js": ["JavaScript", "js", "code"], ".jsx": ["JavaScript", "js", "code"], ".mjs": ["JavaScript", "js", "code"], ".cjs": ["JavaScript", "js", "code"],
  ".ts": ["TypeScript", "js", "code"], ".tsx": ["TypeScript", "js", "code"], ".mts": ["TypeScript", "js", "code"], ".cts": ["TypeScript", "js", "code"],
  ".vue": ["Vue", "js", "code"], ".svelte": ["Svelte", "js", "code"], ".astro": ["Astro", "js", "code"],
  ".py": ["Python", "py", "code"], ".go": ["Go", "go", "code"], ".rs": ["Rust", "rust", "code"],
  ".java": ["Java", "jvm", "code"], ".kt": ["Kotlin", "jvm", "code"], ".kts": ["Kotlin", "jvm", "code"], ".scala": ["Scala", "jvm", "code"],
  ".cs": ["C#", "dotnet", "code"], ".c": ["C", "c", "code"], ".h": ["C", "c", "code"],
  ".cpp": ["C++", "c", "code"], ".cc": ["C++", "c", "code"], ".cxx": ["C++", "c", "code"], ".hpp": ["C++", "c", "code"],
  ".rb": ["Ruby", "rb", "code"], ".php": ["PHP", "php", "code"], ".swift": ["Swift", "swift", "code"], ".dart": ["Dart", "dart", "code"],
  ".lua": ["Lua", "lua", "code"], ".ex": ["Elixir", "ex", "code"], ".exs": ["Elixir", "ex", "code"], ".erl": ["Erlang", "erl", "code"],
  ".hs": ["Haskell", "hs", "code"], ".clj": ["Clojure", "clj", "code"], ".r": ["R", "r", "code"], ".jl": ["Julia", "jl", "code"],
  ".sh": ["Shell", "sh", "code"], ".bash": ["Shell", "sh", "code"], ".zsh": ["Shell", "sh", "code"], ".ps1": ["PowerShell", "ps", "code"],
  ".sql": ["SQL", "sql", "code"], ".graphql": ["GraphQL", "gql", "code"], ".gql": ["GraphQL", "gql", "code"], ".prisma": ["Prisma", "prisma", "code"], ".proto": ["Protobuf", "proto", "code"],
  ".html": ["HTML", "html", "markup"], ".htm": ["HTML", "html", "markup"],
  ".css": ["CSS", "css", "style"], ".scss": ["SCSS", "css", "style"], ".sass": ["Sass", "css", "style"], ".less": ["Less", "css", "style"],
  ".json": ["JSON", "json", "data"], ".jsonc": ["JSON", "json", "data"], ".yaml": ["YAML", "yaml", "config"], ".yml": ["YAML", "yaml", "config"],
  ".toml": ["TOML", "toml", "config"], ".ini": ["INI", "ini", "config"], ".cfg": ["Config", "ini", "config"], ".conf": ["Config", "ini", "config"],
  ".properties": ["Properties", "ini", "config"], ".xml": ["XML", "xml", "data"], ".tf": ["Terraform", "tf", "config"], ".hcl": ["HCL", "tf", "config"], ".gradle": ["Gradle", "gradle", "config"],
  ".md": ["Markdown", "md", "doc"], ".mdx": ["MDX", "md", "doc"],
}

/** Files with no (useful) extension that we still want. */
const NAMED = {
  Dockerfile: ["Dockerfile", "docker", "config"], Makefile: ["Makefile", "make", "config"], Procfile: ["Procfile", "ini", "config"],
  Gemfile: ["Ruby", "rb", "config"], Rakefile: ["Ruby", "rb", "code"], Jenkinsfile: ["Groovy", "groovy", "code"], Justfile: ["Just", "make", "config"],
  "CMakeLists.txt": ["CMake", "cmake", "config"], ".env.example": ["Env template", "env", "config"], ".env.sample": ["Env template", "env", "config"], ".env.template": ["Env template", "env", "config"],
}

const SECRET_NAMES = /^(?:\.env(?:\..+)?|\.npmrc|\.pypirc|\.netrc|\.htpasswd|id_(?:rsa|dsa|ecdsa|ed25519)(?:\.pub)?|.*\.(?:pem|key|p12|pfx|jks|keystore|crt|cer)|credentials(?:\.[a-z]+)?|service[-_]?account.*\.json|secrets?\.(?:json|ya?ml|toml)|.*\.tfstate(?:\.backup)?|.*\.tfvars)$/i
const ENV_TEMPLATES = /^\.env\.(?:example|sample|template|dist|defaults)$/i
const LOCKFILES = /^(?:package-lock\.json|npm-shrinkwrap\.json|yarn\.lock|pnpm-lock\.yaml|bun\.lockb?|Cargo\.lock|poetry\.lock|Pipfile\.lock|composer\.lock|Gemfile\.lock|go\.sum|uv\.lock|pubspec\.lock|.*\.lock)$/i
const DATA_LIKE = new Set(["json", "xml", "yaml", "toml"])
const GENERATED_HEADER = /@generated|DO NOT EDIT|Code generated by|auto-?generated|automatically generated|generated by (?:protoc|openapi|swagger|graphql|prisma|sqlc|bindgen|thrift|webpack|rollup)/i

export const MAX_VISITED = 150_000

export const sha = (s) => crypto.createHash("sha256").update(s).digest("hex")
export const toPosix = (p) => p.split(path.sep).join("/")

export function langInfo(rel) {
  const base = path.posix.basename(rel)
  if (NAMED[base]) return NAMED[base]
  if (/^Dockerfile\./.test(base)) return NAMED.Dockerfile
  if (/^requirements.*\.txt$/i.test(base)) return ["pip requirements", "txt", "config"]
  return LANGS[path.posix.extname(base).toLowerCase()] || null
}

/** Decide whether a file should be read, and why not. Pure — easy to test. */
export function classify(rel, size, opts = {}) {
  const base = path.posix.basename(rel)
  if (SECRET_NAMES.test(base) && !ENV_TEMPLATES.test(base)) return { skip: "secret" }
  if (LOCKFILES.test(base)) return { skip: "lockfile" }
  const info = langInfo(rel)
  if (!info) return opts.explicit ? { info: ["Text", "txt", "doc"] } : { skip: "not-source" }
  const maxBytes = (opts.maxFileKb || 256) * 1024
  if (size === 0) return { skip: "empty" }
  if (size > maxBytes) return { skip: "too-large" }
  if (DATA_LIKE.has(info[1]) && size > 24 * 1024) return { skip: "data-file" }
  return { info }
}

/** Content-level checks once bytes are in memory. */
export function inspectContent(rel, buf, info) {
  const head = buf.subarray(0, 8000)
  if (head.includes(0)) return { skip: "binary" }
  let text = buf.toString("utf8")
  if (text.charCodeAt(0) === 0xfeff) text = text.slice(1)
  const bad = (text.slice(0, 8000).match(/\uFFFD/g) || []).length
  if (bad > 40) return { skip: "binary" }
  text = text.replace(/\r\n?/g, "\n")
  if (!text.trim()) return { skip: "empty" }

  const lines = text.split("\n")
  const kind = info[2]
  if (kind === "code" || kind === "style" || kind === "markup") {
    if (/(?:^|[.-])(?:min|bundle|bundled)\.[a-z]+$/i.test(rel)) return { skip: "minified" }
    let longest = 0
    for (const l of lines) if (l.length > longest) longest = l.length
    if (longest > 1500 && text.length / lines.length > 120) return { skip: "minified" }
  }
  if (GENERATED_HEADER.test(lines.slice(0, 8).join("\n").slice(0, 700))) return { skip: "generated" }
  return { text }
}

/** Read one file for analysis: classify, inspect, redact, hash. Returns {file} or {skip}. */
export function readSource(root, rel, opts = {}) {
  const abs = path.join(root, rel)
  let st
  try {
    st = fs.statSync(abs)
  } catch {
    return { skip: "unreadable" }
  }
  const pre = classify(rel, st.size, opts)
  if (pre.skip) return pre
  let buf
  try {
    buf = fs.readFileSync(abs)
  } catch {
    return { skip: "unreadable" }
  }
  const post = inspectContent(rel, buf, pre.info)
  if (post.skip) return post
  const red = redact(post.text)
  const content = red.text.replace(/\n$/, "")
  return {
    file: {
      path: rel,
      lang: pre.info[0],
      family: pre.info[1],
      kind: pre.info[2],
      size: st.size,
      lines: content.split("\n").length,
      content,
      hash: sha(content).slice(0, 16),
      redactions: red.hits,
    },
  }
}

const NOTABLE = new Set(["too-large", "minified", "generated", "data-file", "binary", "secret"])

/**
 * Walk the project and read every source file worth analysing.
 * Deterministic (sorted), respects .gitignore + .kontxignore + --exclude, never follows symlinks.
 */
export function scanProject({ cwd = process.cwd(), exclude = [], maxFileKb = 256, maxFiles = 4000 } = {}) {
  const root = path.resolve(cwd)
  const home = os.homedir()
  if (root === path.parse(root).root || root === home) {
    throw new ScanError(`Refusing to scan ${root}.`, { hint: "cd into a project folder first — scanning your whole home or drive would be slow and send unrelated files." })
  }

  const matcher = defaultMatcher()
  const readIf = (p) => {
    try {
      return fs.readFileSync(p, "utf8")
    } catch {
      return null
    }
  }
  const rootGitignore = readIf(path.join(root, ".gitignore"))
  if (rootGitignore) matcher.add(rootGitignore, "", 1)
  const kontxIgnore = readIf(path.join(root, ".kontxignore"))
  if (kontxIgnore) matcher.add(kontxIgnore, "", 2)
  if (exclude.length) matcher.add(exclude.join("\n"), "", 2)

  const counts = {}
  const skipped = []
  const bump = (reason, rel) => {
    counts[reason] = (counts[reason] || 0) + 1
    if (rel && NOTABLE.has(reason) && skipped.length < 200) skipped.push({ path: rel, reason })
  }

  const candidates = []
  const stack = [""]
  let visited = 0
  while (stack.length) {
    const rel = stack.pop()
    let entries
    try {
      entries = fs.readdirSync(path.join(root, rel), { withFileTypes: true })
    } catch {
      bump("unreadable")
      continue
    }
    if (rel) {
      const gi = readIf(path.join(root, rel, ".gitignore"))
      if (gi) matcher.add(gi, rel, 1)
    }
    for (const e of entries) {
      if (++visited > MAX_VISITED) {
        throw new ScanError("This folder has too many files to scan.", { hint: "Run kontx from your project root, or add folders to .kontxignore / --exclude." })
      }
      const childRel = rel ? `${rel}/${e.name}` : e.name
      if (e.isSymbolicLink()) {
        bump("symlink")
        continue
      }
      if (e.isDirectory()) {
        if (e.name === ".git" || matcher.ignores(childRel, true)) continue
        stack.push(childRel)
      } else if (e.isFile()) {
        if (matcher.ignores(childRel, false)) {
          bump("ignored")
          continue
        }
        candidates.push(childRel)
      }
    }
  }
  candidates.sort()

  const files = []
  const redactions = []
  for (const rel of candidates) {
    const r = readSource(root, rel, { maxFileKb })
    if (r.skip) {
      bump(r.skip, rel)
      continue
    }
    files.push(r.file)
    for (const h of r.file.redactions) redactions.push({ file: rel, ...h })
    if (files.length > maxFiles) {
      throw new ScanError(`More than ${maxFiles} source files found.`, { hint: "Scope it down: add folders to .kontxignore or use --exclude 'pattern'." })
    }
  }

  return {
    root,
    name: path.basename(root),
    files,
    skipped,
    counts,
    redactions,
    totalLines: files.reduce((s, f) => s + f.lines, 0),
  }
}
