import { VERSION } from "./version.js"

export const estimateTokens = (s) => Math.ceil(String(s).length / 3.5)
export const fmt = (n) => Number(n).toLocaleString("en-US")
export const esc = (s) => String(s).replace(/\|/g, "\\|").replace(/\n/g, " ")
export const trunc = (s, n = 100) => (String(s).length > n ? String(s).slice(0, n - 1) + "…" : String(s))

export function mdTable(headers, rows) {
  if (!rows.length) return "_none_"
  const line = (cells) => `| ${cells.map(esc).join(" | ")} |`
  return [line(headers), line(headers.map(() => "---")), ...rows.map(line)].join("\n")
}

export function relTime(ts) {
  const s = Math.max(0, Math.round((Date.now() - ts) / 1000))
  if (s < 60) return "moments ago"
  if (s < 3600) return `${Math.round(s / 60)}m ago`
  if (s < 86400) return `${Math.round(s / 3600)}h ago`
  return `${Math.round(s / 86400)}d ago`
}

export function renderTree(paths, { maxDepth = 3, maxLines = 70 } = {}) {
  const root = { dirs: new Map(), files: [] }
  for (const p of paths) {
    const parts = p.split("/")
    let n = root
    for (const part of parts.slice(0, -1)) {
      if (!n.dirs.has(part)) n.dirs.set(part, { name: part, dirs: new Map(), files: [] })
      n = n.dirs.get(part)
    }
    n.files.push(parts.at(-1))
  }
  const count = (n) => n.files.length + [...n.dirs.values()].reduce((s, d) => s + count(d), 0)
  const lines = []
  const walk = (n, prefix, depth) => {
    const items = [...[...n.dirs.values()].sort((a, b) => a.name.localeCompare(b.name)).map((d) => ({ d })), ...n.files.sort().map((f) => ({ f }))]
    items.forEach((it, i) => {
      const last = i === items.length - 1
      const branch = last ? "└── " : "├── "
      const next = prefix + (last ? "    " : "│   ")
      if (it.d) {
        if (depth >= maxDepth) lines.push(`${prefix}${branch}${it.d.name}/ (${count(it.d)} files)`)
        else {
          lines.push(`${prefix}${branch}${it.d.name}/`)
          walk(it.d, next, depth + 1)
        }
      } else lines.push(`${prefix}${branch}${it.f}`)
    })
  }
  walk(root, "", 1)
  return lines.length > maxLines ? [...lines.slice(0, maxLines), `… ${lines.length - maxLines} more`].join("\n") : lines.join("\n")
}

export function buildHeader({ command, title, subtitle, project, git, model, aiUsed }) {
  const when = new Date().toISOString().slice(0, 16).replace("T", " ") + " UTC"
  const where = git?.commit ? ` · commit \`${git.commit}\`${git.dirty ? " (+ uncommitted changes)" : ""}` : ""
  const who = aiUsed ? ` · model \`${model}\`` : " · no AI used"
  return [
    `<!-- generated by ownit v${VERSION} — https://github.com/reabot6/ownit -->`,
    `# ownit \`${command}\` — ${project}`,
    "",
    `> ${subtitle}`,
    `> Generated ${when}${where}${who}`,
    "> 🧮 = computed by code from your files (exact) · 🤖 = written by the AI from those facts",
    "",
  ].join("\n")
}

export const footer = () => `\n---\n_Generated by [ownit](https://github.com/reabot6/ownit) v${VERSION}. AI-written sections can be wrong — verify anything important against the code._\n`

/** Normalise model output: unwrap an outer code fence, drop chatty preamble, badge AI headings with 🤖. */
export function cleanAi(text, level = 2) {
  let t = String(text).trim()
  const fenced = t.match(/^```(?:markdown|md)?\n([\s\S]*)\n```$/)
  if (fenced) t = fenced[1]
  const first = t.search(new RegExp(`^#{${level}} `, "m"))
  if (first > 0 && first < 600) t = t.slice(first)
  const hashes = "#".repeat(level)
  let inFence = false
  return t
    .split("\n")
    .map((l) => {
      if (/^```/.test(l)) inFence = !inFence
      if (!inFence && l.startsWith(hashes + " ") && !l.startsWith(hashes + " 🤖")) return `${hashes} 🤖 ${l.slice(level + 1)}`
      return l
    })
    .join("\n")
}

export function missingHeadings(text, expect = []) {
  return expect.filter((h) => !new RegExp(`^#{2,3}\\s*(?:🤖\\s*)?${h.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}`, "mi").test(text))
}
